#define ZOMBIE 0 //僵尸
#define FLAG_ZOMBIE 1 //摇旗僵尸
#define CONEHEAD_ZOMBIE 2 //路障僵尸
#define BUCKETHEAD_ZOMBIE 3 //铁桶僵尸
#define POLE_VAULTING_ZOMBIE 4 //撑杆僵尸
#define NEWSPAPER_ZOMBIE 5 //读报僵尸
#define SCREEN_DOOR_ZOMBIE 6 //铁栅门僵尸
#define FOOTBALL_ZOMBIE 7 //橄榄球僵尸
#define DANCING_ZOMBIE 8 //舞王僵尸
#define BACKUP_DANCER 9 //伴舞僵尸
#define DUCKY_TUBE_ZOMBIE 10 //鸭子救生圈僵尸
#define SNORKEL_ZOMBIE 11 //潜水僵尸
#define ZOMBONI 12 //雪橇车僵尸
#define ZOMBIE_BOBSLED_TEAM 13 //雪橇僵尸小队
#define DOLPHIN_RIDER_ZOMBIE 14 //海豚骑士僵尸
#define JACK_IN_THE_BOX_ZOMBIE 15 //玩偶匣僵尸
#define BALLON_ZOMBIE 16 //气球僵尸
#define DIGGER_ZOMBIE 17 //矿工僵尸
#define POGO_ZOMBIE 18 //跳跳僵尸
#define ZOMBIE_YETI 19 //僵尸雪人
#define BUNGEE_ZOMBIE 20 //蹦极僵尸
#define LADDER_ZOMBIE 21 //扶梯僵尸
#define CATAPULT_ZOMBIE 22 //投石车僵尸
#define GARGANTUAR 23 //伽刚特尔
#define GIGA_GARGANTUAR 24 //暴走伽刚特尔
#define IMP 25 //小鬼僵尸
#define DR_ZOMBOOS 26 //僵王博士
#define PEASHOOTER_ZOMBIE 27 //豌豆射手僵尸
#define WALL_NUT_ZOMBIE 28 //坚果墙僵尸
#define SQUASH_ZOMBIE 29 //窝瓜僵尸
#define JALAPENO_ZOMBIE 30 //火爆辣椒僵尸
#define TALL_NUT_ZOMBIE 31 //高坚果僵尸
#define GATLING_PEA_ZOMBIE 32 //机枪射手僵尸